<?php
/**
 * Townsquare core
 *
 * This module provides the fundamental building blocks for the Townsquare
 * project.
 */ 

include_once('townsquare_core.features.inc');

/**
 * Implements hook_theme().
 */
function townsquare_core_theme() {
  return array(
    'townsquare_login' => array(
      'variables' => array('user' => NULL),
      'template' => 'townsquare-login',
    ),
  );
}

/**
 * Implemenets hook_init()
 */
function townsquare_core_init() {
  drupal_add_css(drupal_get_path('module', 'townsquare_core') .'/css/townsquare-core.css');
}

/**
 * Implements hook_custom_theme().
 *
 * Fix silly features incompatibility with theme.
 */
function townsquare_core_custom_theme() {
  if (arg(2) == 'features' || arg(2) == 'views') {
    return 'seven';
  }
}
