<?php
/**
 * @file
 * townsquare_core.features.node_export_features.inc
 */

/**
 * Implements hook_node_export_features_default().
 */
function townsquare_core_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  array(
    \'vid\' => \'10\',
    \'uid\' => \'0\',
    \'title\' => \'Home page\',
    \'log\' => \'\',
    \'status\' => \'1\',
    \'comment\' => \'1\',
    \'promote\' => \'0\',
    \'sticky\' => \'0\',
    \'vuuid\' => \'36fcfd09-0136-7594-e546-ab619eb1dca4\',
    \'nid\' => \'10\',
    \'type\' => \'page\',
    \'language\' => \'und\',
    \'created\' => \'1323908649\',
    \'changed\' => \'1323908649\',
    \'tnid\' => \'0\',
    \'translate\' => \'0\',
    \'uuid\' => \'14843add-7d36-4684-7d93-55b76ba7f890\',
    \'revision_timestamp\' => \'1323908649\',
    \'revision_uid\' => \'0\',
    \'body\' => array(
      \'und\' => array(
        \'0\' => array(
          \'value\' => \'<p class="big">
  Townsquare is a web application that helps community-based organizations manage volunteers, track program participation, and share institutional knowledge and skills.
</p>

* * *

<div class="clearfix">
  <div class="grid-6 alpha">
    <h2>
      How can I contribute?
    </h2>
    
    <ul>
      <li>
        <a href="http://goo.gl/s8e0o">Watch a short presentation on contributing to Townsquare</a>
      </li>
      <li>
        <a href="/user/register">Set up an account on the development site</a>
      </li>
      <li>
        Test the volunteer management system and the wiki (documentation coming soon!)
      </li>
      <li>
        <a href="http://github.com/freegeekchicago/townsquare/issues/">Create issues on Github</a>.
      </li>
    </ul>
    
    <p>
      <strong>Townsquare is under active development and is not ready for wide deployment</strong>, but we welcome your contributions and assistance. Developers, please contact <a href="http:/twitter.com/eads">David Eads</a> to get access to the development group.
    </p>
  </div>
  
  <div class="grid-5 push-1 omega">
    <h2>
      License
    </h2>
    
    <p>
      Townsquare is released under the <a href="http://www.gnu.org/licenses/gpl.html">GNU General Public License v3.0.</a>
    </p>
    
    <h2>
      About Townsquare
    </h2>
    
    <p>
      Townsquare is a project of <a href="http://freegeekchicago.org">FreeGeek Chicago</a>. Townsquare is proudly built on <a href="http://drupal.org">Drupal</a>.
    </p>
    
    <p>
      <strong>Townsquare is designed to address the specific needs of our volunteer-driven, cooperatively managed organization.</strong> Townsquare is envisioned as a tool in a toolkit that includes accounting, point of sale, inventory management, campaign management, and online fundraising.
    </p>
  </div>
</div>

* * *

<p class="big">
  The current Townsquare version is <a href="https://github.com/freegeekchicago/townsquare/zipball/7.x-1.x-alpha-4"><strong>alpha-4</strong></a>.
</p>

<div class="clearfix">
  <div class="grid-6 alpha">
    <h3>
      Component status
    </h3>
    
    <ul>
      <li>
        <strong>Volunteer manager</strong>: Basic hour tracking system is fairly stable, credit and notification system still needed.
      </li>
      <li>
        <strong>Wiki:</strong> Editing UI stable but limited, future architecture to be determined.
      </li>
      <li>
        <strong>Conversation system:</strong> Requires long term planning; no development expected until mid 2012.
      </li>
    </ul>
  </div>
  
  <div class="grid-5 push-1 omega">
    <h3>
      Short-term (alpha-5) goals
    </h3>
    
    <ul>
      <li>
        Conduct wiki needs assessment.
      </li>
      <li>
        Get design assistance.
      </li>
      <li>
        Develop Drupal makefile and install profile.
      </li>
      <li>
        Participant self sign-up and better user handling.
      </li>
    </ul>
  </div>
</div>\',
          \'summary\' => \'\',
          \'format\' => \'markdown_advanced\',
          \'safe_value\' => \'<p class="big">
  Townsquare is a web application that helps community-based organizations manage volunteers, track program participation, and share institutional knowledge and skills.
</p>

<hr />

<div class="clearfix">
  <div class="grid-6 alpha">
    <h2>
      How can I contribute?
    </h2>
    
    <ul>
      <li>
        <a href="http://goo.gl/s8e0o">Watch a short presentation on contributing to Townsquare</a>
      </li>
      <li>
        <a href="/user/register">Set up an account on the development site</a>
      </li>
      <li>
        Test the volunteer management system and the wiki (documentation coming soon!)
      </li>
      <li>
        <a href="http://github.com/freegeekchicago/townsquare/issues/">Create issues on Github</a>.
      </li>
    </ul>
    
    <p>
      <strong>Townsquare is under active development and is not ready for wide deployment</strong>, but we welcome your contributions and assistance. Developers, please contact <a href="http:/twitter.com/eads">David Eads</a> to get access to the development group.
    </p>
  </div>
  
  <div class="grid-5 push-1 omega">
    <h2>
      License
    </h2>
    
    <p>
      Townsquare is released under the <a href="http://www.gnu.org/licenses/gpl.html">GNU General Public License v3.0.</a>
    </p>
    
    <h2>
      About Townsquare
    </h2>
    
    <p>
      Townsquare is a project of <a href="http://freegeekchicago.org">FreeGeek Chicago</a>. Townsquare is proudly built on <a href="http://drupal.org">Drupal</a>.
    </p>
    
    <p>
      <strong>Townsquare is designed to address the specific needs of our volunteer-driven, cooperatively managed organization.</strong> Townsquare is envisioned as a tool in a toolkit that includes accounting, point of sale, inventory management, campaign management, and online fundraising.
    </p>
  </div>
</div>

<hr />

<p class="big">
  The current Townsquare version is <a href="https://github.com/freegeekchicago/townsquare/zipball/7.x-1.x-alpha-4"><strong>alpha-4</strong></a>.
</p>

<div class="clearfix">
  <div class="grid-6 alpha">
    <h3>
      Component status
    </h3>
    
    <ul>
      <li>
        <strong>Volunteer manager</strong>: Basic hour tracking system is fairly stable, credit and notification system still needed.
      </li>
      <li>
        <strong>Wiki:</strong> Editing UI stable but limited, future architecture to be determined.
      </li>
      <li>
        <strong>Conversation system:</strong> Requires long term planning; no development expected until mid 2012.
      </li>
    </ul>
  </div>
  
  <div class="grid-5 push-1 omega">
    <h3>
      Short-term (alpha-5) goals
    </h3>
    
    <ul>
      <li>
        Conduct wiki needs assessment.
      </li>
      <li>
        Get design assistance.
      </li>
      <li>
        Develop Drupal makefile and install profile.
      </li>
      <li>
        Participant self sign-up and better user handling.
      </li>
    </ul>
  </div>
</div>
\',
          \'safe_summary\' => \'\',
        ),
      ),
    ),
    \'name\' => \'\',
    \'picture\' => \'0\',
    \'data\' => NULL,
    \'path\' => array(
      \'pid\' => \'1\',
      \'source\' => \'node/10\',
      \'alias\' => \'home\',
      \'language\' => \'und\',
    ),
    \'menu\' => array(
      \'link_title\' => \'\',
      \'mlid\' => 0,
      \'plid\' => 0,
      \'menu_name\' => \'main-menu\',
      \'weight\' => 0,
      \'options\' => array(),
      \'module\' => \'menu\',
      \'expanded\' => 0,
      \'hidden\' => 0,
      \'has_children\' => 0,
      \'customized\' => 0,
      \'parent_depth_limit\' => 8,
      \'description\' => \'\',
      \'enabled\' => 1,
    ),
    \'node_export_drupal_version\' => \'7\',
    \'#_export_node_encode_object\' => \'1\',
  ),
)',
);
  return $node_export;
}
