<?php
/**
 * Townsquare core
 *
 * This module provides the fundamental building blocks for the Townsquare
 * project.
 */ 

include_once('townsquare_core.features.inc');

/**
 * Implements hook_theme().
 */
function townsquare_core_theme() {
  return array(
    'townsquare_login' => array(
      'variables' => array('user' => NULL),
      'template' => 'townsquare-login',
    ),
  );
}

function townsquare_core_init() {
  drupal_add_css(drupal_get_path('module', 'townsquare_core') .'/css/townsquare-core.css');
}
