<?php
/**
 * @file
 *
 * Reports for FreeGeek
 */

/**
 * Implements hook_menu().
 */
function freegeek_townsquare_reports_menu() {
  $items = array();
  $items['townsquare/reports'] = array(
    'title' => 'Reports', 
    'description' => 'Generate reports', 
    'page callback' => 'freegeek_townsquare_reports', 
    'page arguments' => array(2, 3), 
    'access callback' => TRUE,
  );
  return $items;
}



function freegeek_townsquare_reports($format, $limit = 500) {
  $result = array();
  $skipped = 0;
  $total_sessions = 0;
  $total_hours = 0;
  $query = new entityfieldquery;
  $query
    ->entitycondition('entity_type', 'node')
    ->propertycondition('type', 'volunteer_session')
    ->range(0, $limit);

  $i += $inc;
  $result = $query->execute();
  if ($result) {
    $sessions = entity_load('node', array_keys($result['node']));
    foreach ($sessions as $nid => $session) {
      $event_node = array_pop(field_get_items('node', $session, 'field_session_event'));
      $event = array_pop(entity_load('node', array($event_node['target_id'])));
      try {
        $event_date_field = array_pop(field_get_items('node', $event, 'field_event_date'));
        $event_date = new DateObject($event_date_field['value'], $event_date_field['timezone']);
        $duration = array_pop(field_get_items('node', $session, 'field_session_duration'));
        $value = $event_date->format($format);
        $value = str_replace(array('0201', '0209'), array('2010', '2009'), $value);
        if (empty($results[$value])) {
          $results[$value] = array( 
            array(
              'data' => $value,
              'header' => true,
            ),
            (float) $duration['value'],
            1, // sessions
          );
        } else {
          $total_sessions += 1;
          $total_hours += (float) $duration['value'];
          $results[$value][1] += (float) $duration['value']; 
          $results[$value][2] += 1;
        }
      } 
      catch (Exception $e) {
        $skipped++;
      }
    }
  }
  $header = array('', 'Hours', 'Sessions');
  ksort($results);
  $markup = array(
    '#type' => 'markup',
    '#prefix' => '<p>',
    '#suffix' => '</p>',
  );

  $output = array(
    $markup + array(
      '#markup' => t('Total sessions: !n sessions', array('!n' => $total_sessions)),
    ),
    $markup + array(
      '#type' => 'markup',
      '#markup' => t('Total hours: !n hours', array('!n' => $total_hours)),
    ),
    $markup + array(
      '#type' => 'markup',
      '#markup' => t('Average session length: !n hours', array('!n' => round($total_hours / $total_sessions, 1))),
    ),
    $markup + array(
      '#type' => 'markup',
      '#markup' => t('Debug: Skipped !n bad sessions', array('!n' => $skipped)),
    ),
    array(
      '#attributes' => array('id' => 'freegeek-report-' . $format),
      '#prefix' => '<h1>'. $format .'</h1>',
      '#theme' => 'table',
      '#header' => $header,
      '#rows' => $results,
    ),
    '#cache' => array(
      'keys' => array('freegeek_townsquare_reports'),
      'bin' => 'cache',
      'expire' => time() + 60000,
      'granularity' => DRUPAL_CACHE_PAGE,
    ),
  );
  drupal_add_js(libraries_get_path('jqplot') . '/jquery.jqplot.min.js');
  drupal_add_js(libraries_get_path('jqplot') . '/plugins/jqplot.categoryAxisRenderer.js');
  drupal_add_js(libraries_get_path('jqplot') . '/plugins/jqplot.barRenderer.js');
  drupal_add_js(libraries_get_path('jqplot') . '/plugins/jqplot.canvasTextRenderer.js');
  drupal_add_js(libraries_get_path('jqplot') . '/plugins/jqplot.canvasAxisTickRenderer.js');
  drupal_add_css(libraries_get_path('jqplot') . '/jquery.jqplot.css');
  drupal_add_js(libraries_get_path('tablechart') . '/jquery.tablechart.js');
  drupal_add_js(drupal_get_path('module', 'freegeek_townsquare_reports') . '/js/freegeek_townsquare_reports.js');
  return $output;
}
