<?php
/**
 * @file
 */

function freegeek_townsquare_reports_menu() {
  $items = array();
  $items['townsquare/reports'] = array(
    'title' => 'Reports', 
    'description' => 'Generate reports', 
    'page callback' => 'freegeek_townsquare_reports', 
    'page arguments' => array(), 
    'access callback' => TRUE,
  );

  return $items;
}


function _freegeek_townsquare_reports_process_session($session, $event, $event_date, &$results) {
  $duration = array_pop(field_get_items('node', $session, 'field_session_duration'));

  $formats = array(
    'by_year' => 'Y',
    'by_month' => 'm-F',
    'by_day' => 'l',
    'by_year_and_month' => 'Y-m-F',
    'by_year_and_day' => 'Y-l',
  );
  foreach ($formats as $key=>$format) {
    $value = $event_date->format($format);
    $value = str_replace(array('0201', '0209'), array('2010', '2009'), $value);
    if (empty($results[$key][$value])) {
      $results[$key][$value] = array( 
        array(
          'data' => $value,
          'header' => true,
        ),
        $duration['value'],
        1, // sessions
      );
    } else {
      $results[$key][$value][1] += $duration['value']; 
      $results[$key][$value][2] += 1;
    }
  }
}

function freegeek_townsquare_reports() {
  $result = array(
    'by_year' => array(),
    'by_month' => array(),
    'by_month_and_year' => array(),
    'by_day_and_year' => array(),
  );

  $skipped = 0;
  for ($i = 0; $i < 2500; $i += 500) {
    $query = new entityfieldquery;
    $query
      ->entitycondition('entity_type', 'node')
      ->propertycondition('type', 'volunteer_session')
      ->range($i, $i + 500);

    $result = $query->execute();

    if ($result) {
      $sessions = entity_load('node', array_keys($result['node']));
      foreach ($sessions as $nid => $session) {
        if (!$session->uid) {
          break; 
        }
        $event_node = array_pop(field_get_items('node', $session, 'field_session_event'));
        $event = array_pop(entity_load('node', array($event_node['target_id'])));
        try {
          $event_date_field = array_pop(field_get_items('node', $event, 'field_event_date'));
          $event_date = new DateObject($event_date_field['value'], $event_date_field['timezone']);
          _freegeek_townsquare_rules_reports_process_session($session, $event, $event_date, $results);
        } 
        catch (Exception $e) {
          $skipped++;
        }
      }
    }
  }
  $output = '';
  $header = array('', 'Hours', 'Sessions');
  foreach ($results as $type=>$result) {
    $output .= '<h1>'. $type .'</h1>';
    ksort($result);
    $output .= theme('table', array('header' => $header, 'rows' => $result));
  }
  return $output;
}
